predixdesignsystem/px-data-grid

- demo/px-data-grid-remote-data-provider-demo.html
Follow-up for the remote-data filtering https://github.com/vaadin/px-data-grid/pull/81
> Use size from API server, pass it to the callback method

- demo/px-data-grid-column-demo.html
- demo/px-data-grid-demo.html
- px-data-grid-column.html
- px-data-grid-selection-column.html
- px-data-grid.html
- test/px-data-grid-test.js
Still in WiP, but:
- This will fix select/deselect behavior without items
- And disables select all for remote data source totally (as it might be really expensive)
Still to do:
- Actual single selection mode
> Fix mass selection on local data mode, disable on remote

- demo/px-data-grid-column-demo.html
- demo/px-data-grid-demo.html
- px-data-grid.html
- test/columns-api.js
I added updateColumns API to tell px-grid to really update columns, as updating arrays is real pain with polymer sometimes.
Also added new API for table actions. No functions, just ids and then table-action events. This to work around no functions in JSON limitation.
> Force column update API and changed table actions API

- demo/px-data-grid-remote-data-provider-demo.html
- px-data-grid.html
Resolving one of my tech debts related to the remote data provider.
`_populateTableColumns()` is now called internally, as it should.
> Call _populateTableColumns internally after receiving a new set of data

- demo/index.html
- demo/px-data-grid-paginated-demo.html
- px-data-grid-navigation.html
- px-data-grid-paginated.html
- px-data-grid.html
- test/px-data-grid-fixture.html
- test/px-data-grid-navigation-test.js
- test/px-data-grid-paginated-test.js
Ready to review and merge if no major problems are found.  Sorry in advance for less than optimal git use and massive PR.
**Major changes/additions/notes:**
- Removed navigation/paging from the normal grid class.
- Added wrapper class for paginated grid (px-data-grid-paginated).
- Added and updated tests for navigation component (UI part of pagination).
- Tested successfully with local data array and remote data provider from px-data-grid demo.
- Working will all implemented grid features except for row selection.  Selection works, but toggling it causes some issues.
**Key parts to review:**
- The px-data-grid-pagination class wraps the supplied data provider (or local data provider) before handing it to the px-data-grid.  This way we can manipulate the params and the callback objects, …
> Navigation component fixes, tests, and pagination data provider logic

- index.html
- px-data-grid.html
Styles for data-grid are moved from `demo/index.html` to the component by itself.
Working jsfiddle with the `include-styles-into-component` branch dependency: https://jsfiddle.net/6r5htd05/89/
> Include styles into component

- demo/px-data-grid-demo.html
- px-data-grid.html
PR for https://github.com/vaadin/px-data-grid/issues/144
Simple boolean property that toggles ‘height: auto’ on vaadin grid.  This makes the grids height automatically match the number of rows.
> adding simple auto height flag to grid

- px-data-grid-header-cell.html
- px-data-grid-theme.html
Fixes #179
Tested manually in IE11, Firefox and Chrome, the look-n-feel is now the same for all browsers.
> fix(header-cells): fix header cells height for IE11, set it to 35px according to specs

- px-data-grid-selection-column.html
- px-data-grid.html
Fixes #196 #197 
Tested manually in IE11, Firefox and Chrome, the look-n-feel is now the same for all browsers.
> fix(selection-column): get rid of .selection-count, use vaadin-checkbox label instead

- px-data-grid.html
Fixes #105 
`column.name` could be undefined as well, we shouldn't rely on it. Instead, print the whole `column` object.
> fix(custom-column): add JSON.stringify(column) to warning message

- px-data-grid.html
Looks like the public method for toggling details container got remove at some point.  So this is to add it back in.
> API for toggling row details

- px-data-grid-cell-content-wrapper.html
- px-data-grid.html
> When resorting while in edit, do not show fields at wrong row

- .travis.yml
Current master is failing: https://travis-ci.org/vaadin/px-data-grid/builds/326384940
Reason: https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
`chrome-sandbox` needs `sudo` in order to run :this-is-fine:
> Add sudo: true to Travis config for running chrome-sandbox

- px-data-grid.html
> fix(table-data): run _tableDataChanged observer only if px-data-grid is attached

- sass/px-data-grid.scss
> Use flex-start, not center as default align of cell content

- css/px-data-grid-selection-column-styles.html
- demo/px-data-grid-column-demo.html
- demo/px-data-grid-custom-renderer-demo.html
- demo/px-data-grid-demo.html
- demo/px-data-grid-highlight-demo.html
- demo/px-data-grid-paginated-demo.html
- demo/px-data-grid-remote-data-provider-demo.html
- demo/px-data-grid-row-details-demo.html
- px-data-grid-paginated.html
- px-data-grid.html
New attribute to allow define the height of actual grid inside
px-data-grid. Currently supported values are undefined and
'default' both just using the default heigth of vaadin-grid. Then
'auto' that is as old auto-height. And then any non-relative
CSS height value (eg. '300px'). This does not yet support pairing
sizing with define height of px-data-grid. That is new requirement
and needs to be done later.
Fixes #333
> API CHANGE, replace auto-height with grid-height

- demo/px-data-grid-paginated-demo.html
- gulpfile.js
- px-data-grid-paginated-api.json
- px-data-grid-paginated.html
Allows users to redefine the options offered. Fix paginated demo page (or element name and wrong API listing).
Fixes #357
> Add missing documentation and property to demo

- px-data-grid-paginated.html
Fixing #373
Was missing the px-data-grid.html import in the px-data-grid-paginated.html file.
> Adding missing import for paginated grid (#373)

- bower.json
- px-data-grid-header-cell.html
- px-data-grid.html
Fixes #417
Also in headers does not need to unselect selections, and can just
use the click listener directly.
> Use new API in px-dropdown to offer unselectable options

- px-data-grid-filterable-mixin.html
I assume "Greater than" and "Less than" should work strictly. Changed conditions according to this assumption.
> Changed not strict conditions to strict ones

- demo/px-data-grid-demo.html
- demo/px-data-grid-paginated-demo.html
- px-data-grid-paginated.html
- px-data-grid.html
Fixes #416
Also remove _ prefix from functions that are required to generate
CSV export in demo. And add matching functions to paginated
version that will pass the call to grid inside. Also pass table
action event from px-data-grid to users of px-data-grid-paginated.
All this boiler plate might become useful in the future, as
behavior of these functions and events might change in paginated
version. Also getData will now just return all shown data, not
all data. I assume this is correct for paginated version.
> Add table actions to paginated version of px-data-grid

- px-data-grid-theme.html
Without IE world would be much better and webdevs so much happier.
This is the 3rd approach I tried. The ugliest one, but works in IE11.
Fixes #469
> Fix focus state outline for highlighted cells

- demo/px-data-grid-demo.html
- px-data-grid-filter.html
- px-data-grid-filterable-mixin.html
- px-data-grid-filters-modal.html
- px-data-grid-paginated.html
- px-data-grid.html
- test/filterable.js
Wildcard -> regex were missing ^ and $ from the rule. Also improved the undefined, empty and * cases. And wrote more tests.
Also improves save filters checkbox action, it's now optional. As not all application want to save filters.
Fixes #512
> Fix wildcard regex generation and save filters

- px-data-grid-cell-content-wrapper.html
- px-data-grid.html
Connected to https://github.com/vaadin/px-data-grid/issues/474
This change fixes the focusing of `string` and `number` renderers. The `date` still doesn't work because of `px-datetime-picker` doesn't implement `.focus()` method on itself. 
I reported that issue to them: https://github.com/PredixDev/px-datetime-picker/issues/30
> Fix keyboard a11y for editable cells inputs

- px-data-grid-filters-preview.html
However, doesn't work on px-demo but should work on non demo-apps. Checked with GE devs that this is a known issue on px-tooltip relating to overflows.
Fixes #521
> Enabled smartOrientation on px-tooltips

- bower.json
- px-data-grid-filter.html
- px-data-grid-filters-modal.html
- sass/px-data-grid-filters-modal.scss
Use new px-modal that allows to inject all 3 buttons in. Doesn't yet fix the sizing issues when window is resized anyhow. But will make buttons clickable on all browsers (earlier the unused slots overlapped buttons, now buttons are in slots).
Related to #363
> Make advanced filter use slots of px-modal

- sass/px-data-grid-sorter.scss
Added new variable and fixed grid column header text flexbox for controlling how text overflow is handled. Default changed to use ellipsis instead of wrap.
Fixes: #296
> Grid column header wrap/ellipsis

- px-data-grid-paginated.html
- px-data-grid.html
API change, renamed defaultColumnFlex to defaultColumnFlexGrow.
Added missing mapping of these values from px-data-grid-paginated\
to px-data-grid.
Fixes #530
> Improve documentation of defaultColumn Width and FlexGrow

- sass/px-data-grid-filter.scss
We updated the px-modal to handle overflowing content in the "body" slot by scrolling the entire modal. This is different from the spec where the header/footer of the modal are fixed and only the body scrolls. The GE designers have accepted and said this approach is OK for now.
This PR fixes a collision of the two approaches. Before to make the modal work correctly the px-data-grid-filter component created its own scrolling region if its contents were too tall. This leads to a double scroll bar:
I took the overflow scroll behavior out of px-data-grid-filter, so the modal can decide how its contents should scroll. This is the result:
> Fix double scroll bars in advanced filtering modal

- px-data-grid-action-column.html
- px-data-grid-filter-entity.html
- px-data-grid-filter-section.html
- px-data-grid-header-cell.html
- px-data-grid-navigation.html
- px-data-grid.html
Connected to https://github.com/PolymerElements/iron-overlay-behavior/pull/263
Currently any `px-dropdown` will disable scrolling of the whole document, IMO that's unwanted and `px-dropdown` should refit in viewport instead of blocking it.
> Add allow-outside-scroll to all px-dropdowns

- bower.json
- examples/renderer-number-config.html
- px-data-grid-number-renderer.html
- test/helpers.html
- test/px-data-grid-fixture.html
- test/renderers.js
* When the px-data-grid-number-renderer is used for a column the
developer can pass new rendererConfig options, including
rendererConfig.displayFormat, which should be set to a valid
numbro.js string used to format the number before it is displayed.
* Additional renderer options are exposed to customize how numbro.js
formats the value. See the px-data-grid-number-renderer.html file
for a full list.
* Throws an error when given a value that cannot be parsed
to a number, but recovers and renders the value anyway.
* Adds new renderer tests to cover these cases.
See examples/renderer-number-config.html for a demo.
Supersedes #707. Final fixes for #624.
> Add display formatting for number renderer

- test/helpers.html
- test/renderers.js
Polyfills are great. Read the comment on the `getShadowRootShallowInnerText()` in the diff to see what is going on.
> Fix number renderer tests

- px-data-grid-filter-entity.html
- sass/px-data-grid-filter-entity.scss
Related to #630 
Using fullWidth property in order to make rangepickers span entire container width.  px-rangepicker has default min width of 250, so in order to get horizontal layout I’ve removed the min width.
> Fixing width for px-rangepicker in filter dialog

- px-data-grid-date-renderer.html
- px-data-grid-filter-entity.html
Adds the `hoist` property to fix stacking context issues with datetime components.
In master, rangepickers used inside the advanced filter modal do not lay out on top of the modal and are cut off.
Steps to reproduce:
1. Pull latest from master branch
2. Wipe out bower_components and re-run bower install
3. Serve the grid
4. Open the "date time" demo page
5. Generate some data
6. Activate the advanced filter option
7. Click the table filter button to open the advanced filter modal
8. Create a new filter of type "Date time"
9. Click the range picker field
10. The range picker will open with the bottom cut off
Screenshot before this PR:
Screenshot after this PR with the hoist fix:
> Add hoist property to datetime components to fix stacking context issues

- px-data-grid-header-cell.html
In master with the latest px-dropdown the column header action menu dropdowns are not opening.
Steps to reproduce:
1. Pull latest from `master` branch
2. Wipe out bower_components and re-run `bower install`
3. Serve the grid
4. Open the docs page
5. Click on the column header action menu (three dots)
This fix solves an issue that appeared after [px-dropdown v4.7.1](https://github.com/PredixDev/px-dropdown/releases/tag/v4.7.1) was released.
Internally, px-dropdown is listening for an event called 'tap' on
its trigger. That's for legacy reasons. 'tap' is a Polymer 1.x
concept that was meant to normalize click events in touch
and mouse environments. To maintain compatability going forward
with px-dropdown it will continue to use the 'tap' event instead
of the 'click' event.
Because of this, …
> Cancel tap and click events

- px-data-grid-header-cell.html
Fix for column header dropdown not opening - needs tap/gesture support mixin addition.
Picking up latest px-dropdown, column header dropdown was not responding to tap event. Addition of gesture support mixin fixes this.
> Fix for column header dropdown not opening

- test/renderers.js
- test/selection.js
* Wait a bit longer before selection tests with flush. Right now the test is running before event listeners bind, causing the grid to fail to pick up the test click on a cell to select.
* Trim the text gotten from the DOM for the renderer tests, because IE returns text with a bunch of spaces around it.
> Test fixes for IE

- px-data-grid-filter-entity.html
- px-data-grid-filter-section.html
- px-data-grid-filter.html
- px-data-grid-filters-modal.html
- px-data-grid.html
Depends on https://github.com/predixdesignsystem/px-datetime-common/pull/19 which fix this overflow issue with the timezone dropdown:
> Add use-timezones boolean property to toggle timezones in advanced filtering

- demo/px-data-grid-demo.html
- px-data-grid-date-renderer.html
- px-data-grid-filter-entity.html
- px-data-grid-filterable-mixin.html
- px-data-grid-filters-preview.html
- px-data-grid-paginated.html
- px-data-grid.html
- test/.eslintrc.json
- test/column-dropdown-menu.js
- test/filterable.js
- test/generated-columns.js
- test/helpers.html
- test/px-data-grid-fixture.html
- test/renderers.js
- test/row-details.js
- test/timezones.js
Adding timezone support to px-data-grid.  The application can now specify what timezone the column's data is in, as well as what timezone to display it as.  All existing features such as editing, sorting, and filtering support this.  Anything timestamp/date that is visible will use the display timezone (instead of the data's original timezone).  The underlying data is always kept in the original timezone and format.
Example of a date column with timezones specified:
```
{
name: 'Appointment',
path: 'appointment',
filterByTime: true,
renderer: 'px-data-grid-date-renderer',
dateFormat: {
format: 'YYYY-MM-DD HH:mm',
timezone: 'UTC' // data's timezone
},
rendererConfig: {
hideTime: false,
displayFormat: 'MM/DD/YYYY HH:mm',
timezone: 'America/Los_Angeles', // timezone to be shown …
```
> Adding timezone support

- px-data-grid-cell-content-wrapper.html
- px-data-grid-renderer-mixin.html
Passes the tableData item aka row to the renderer mixin, so renderers can know things about the object used to create them.
Useful for examples like this, a button that when clicked fires a custom event with its item:
```html
<dom-module id="custom-button-renderer">
<template>
<button on-click="_onClick">
Register User
</button>
</template>
<script>
{
class CustomButtonRenderer extends Predix.DataGridRendererMixin(Polymer.Element) {
static get is() { return 'custom-button-renderer'; }
static get properties() {
return {};
}
_onClick() {
const { column, item, value } = this;
const e = new CustomEvent('custom-button-cell-clicked', {
detail: { column, item, value },
bubbles: true,
composed: true
});
this.dispatchEvent(e);
}
}
window.customElements.define(CustomButtonRenderer.is, …
```
> Pass item to renderer, add item property to renderer mixin

- demo/px-data-grid-demo.html
- demo/px-data-grid-paginated-demo.html
Adds a demo for px-data-grid-paginated. Uses the same options from px-data-grid, and adds the `selectablePageSizes` property that is unique to px-data-grid-paginated.
> Add demo for px-data-grid-paginated

- px-data-grid-date-renderer.html
- px-data-grid-filter-entity.html
- px-data-grid-filter-section.html
- px-data-grid-filter.html
- px-data-grid-filters-modal.html
- px-data-grid.html
* Date renderer now defaults to include time zone (short hand).
* Date render in edit mode show time zone but does not allow user to edit it.
* Advanced filtering dialog shows time zone but does not allow user to edit it.
> Setting defaults to show non-editable timezone

- px-data-grid-filter-entity.html
Column `rendererConfig` object contains two props:
* `datePickerDateFormat`
* `datePickerTimeFormat`
These two properties now get applied to the `px-rangepicker` in the filter dialog.
> Mapping date and time formats to filter dialog range picker

- px-data-grid.html
- test/helpers.html
- test/items-without-ids.js
Now actions columns are wrapped into `<vaadin-grid-column-group frozen>` to prevent mixing them with other columns when doing reordering: 
Notice, that users will be still able to reorder 2 action column. If that is not the desired behavior, let me know.
> Use <vaadin-grid-column-group> for action columns to prevent mixing them with data columns

- bower.json
- package-lock.json
- package.json
- px-data-grid.html
Workaround for an infinite scrolling bug on grids which occurs when the sum of all column width exceeds the containing element width.
**Before:**
**After:**
> Unfroze row action column.

- .travis.yml
- bower.json
- package.json
Fix #801 bumped the version number in bower.json and package.json to 1.0.3 - however this version number had already been released by @sks (without updating either of those files).
This bumps the version to 1.0.4 which will now be used to release the fix in #801.
> Bumping to 1.0.4

- HISTORY.md
- bower.json
- package-lock.json
- package.json
- px-data-grid-api.json
- px-data-grid-paginated-api.json
- px-data-grid.html
When single-select is being used, the removal of the item from the selectedItems list is triggering the same event logic as when new data is set (clear selectedItems).
This differs from the removal of the item in multi-select, where the deselected item is popped from the list, triggering the splice event flow.
By changing the single-select removal to use the splice event flow instead of the clear event flow, we make the events across single-select and multi-select consistent. Using the selected-item-changed event becomes more consistent across these two selection modes.
> Single-select removal

- px-data-grid-navigation.html
- px-data-grid-paginated.html
Some missing data bindings for a proper i18n: 
- `resources` not bound from parent `px-data-grid-paginated` to parent `px-data-grid`
- `localize` missing in a `px-data-grid-navigation` binding
> missing bindings for i18n
