demo/px-data-grid-demo.html, px-data-grid-theme.html
=> Added styles for column reordering

px-data-grid-theme.html
Hopefully this simple fix is enough?
=> Add bottom edge border to vaadin-grid, issue #91

bower.json, index.html, px-data-grid.html
=> Switch px-theme with checkbox

px-data-grid-array-data-provider-mixin.html, px-data-grid-header-cell.html, px-data-grid.html, test/px-data-grid-test.js
1) Move column to the very first place after freezing
2) Move column to lastFrozen + 1 position after unfreezing
3) Fix px-dropdown overlay issue
Fixes #5
=> Move column to the very first place after freezing

demo/px-data-grid-column-demo.html, px-data-grid-cell-content-wrapper.html, px-data-grid-renderer-mixin.html, px-data-grid-string-renderer.html, px-data-grid.html, test/columns-api.js, test/helpers.html
1) Column cell renderer
2) API for renderers in the mixin
3) Inline editing for strings
Fixes #29
=> Inline editing

px-data-grid.html
This not final way to do action menu, but just to repair custom actions for now.
=> Fix action menu custom functions

px-data-grid-column.html, px-data-grid-selection-column.html, px-data-grid.html
Added required filtering, to not show selection column in action menu. Or anyway perform normal column actions with select column.
=> Do not show selection column in action menu

px-data-grid-cell-content-wrapper.html, px-data-grid-renderer-mixin.html
=> Added key events for inline editing

bower.json, px-data-grid-selection-column.html, px-data-grid.html, test/column-dropdown-menu.js, test/px-data-grid-fixture.html
Not sure if this should be merged (will talk with customer tomorrow). But makes selection column frozen, and makes sure it goes to the left when toggling selectable (now if any column have been frozen before toggling selectable, it will not go to the left).
Now for just review if code looks good, do not merge yet.
=> Makes sure selection column stays on the left

demo/px-data-grid-demo.html, px-data-grid-header-cell.html, px-data-grid-selection-column.html, px-data-grid-theme.html, px-data-grid.html
Fixes https://github.com/vaadin/px-data-grid/issues/9
=> Group by column

sass/px-data-grid-light-theme.scss
=> Fix to issues #133 and #134

px-data-grid-column.html, px-data-grid-header-cell.html, px-data-grid.html
Follow-up for https://github.com/vaadin/px-data-grid/pull/126
=> Disable group by column in case of remote data provider

px-data-grid-column.html, px-data-grid.html
Follow-up for https://github.com/vaadin/px-data-grid/pull/126
=> Fix grouping by column for custom columns

px-data-grid-navigation.html, px-data-grid-paginated.html
- fixing number of pages rounding bug
- get page number from event model instead of innerText
=> fixing bugs in pagination PR

demo/px-data-grid-column-demo.html, demo/px-data-grid-demo.html, demo/px-data-grid-highlight-demo.html, demo/px-data-grid-paginated-demo.html, demo/px-data-grid-remote-data-provider-demo.html, px-data-grid-paginated.html, px-data-grid.html, test/column-dropdown-menu.js, test/selection.js
As asked, replace selectable and multiSelect properties with single selectionMode property.
=> Replace selectable and multiSelect with selection-mode

px-data-grid-header-cell.html
=> Fix hiding column dropdown icon

demo/px-data-grid-column-demo.html
=> Do not wrap JS calls to properties of demo page

px-auto-filter-field.html, px-data-grid.html
=> Adjust action bar spacing and move magnifying glass to right

demo/px-data-grid-paginated-demo.html, px-data-grid-paginated.html
adding autoHeight true as default for paginated grid, adding autoHeight to pagination demo page
=> Pagination to have auto heigh true for default, adding auto height to pagination demo

px-data-grid.html, test/.eslintrc.json, test/auto-filter.js, test/column-dropdown-menu.js, test/helpers.html
Fixes https://github.com/vaadin/px-data-grid/issues/160
=> Fix 'group by column' for polyfilled browsers

px-data-grid.html, sass/px-data-grid-dark-theme.scss, sass/px-data-grid-light-theme.scss
Fixing issues #186 and #185 and make yellow default highlight.
And adjust default line-height to 40px, with fix to Issue #183
=> Again adjusting colors of light theme

px-data-grid-theme.html
=> Remove undefined style vars usage

px-data-grid.html
=> fix(selection-column): vertical alignment of select-all

px-data-grid.html
=> fix(selection-column): reset selectedItems when switch to single-selection mode

px-data-grid-selection-column.html
=> fix(selection-column): fix vaadin-radio-button vertical alignment

px-data-grid-sorter.html, sass/px-data-grid-sorter.scss
=> Move CSS to sass file

px-data-grid.html
- Fixing #208: setting details toggle column as frozen
=> Fixing #208 - Freezing details toggle column

test/.eslintrc.json, test/get-data.js, test/helpers.html, test/px-data-grid-fixture.html, test/px-data-grid-paginated-test.js
=> Tests for getData method of px-data-grid

px-data-grid.html
=> Replace .startsWith with .indexOf

px-data-grid-date-renderer.html, px-data-grid-number-renderer.html, px-data-grid-renderer-mixin.html, px-data-grid-string-renderer.html
=> Make sure validation error tooltips are not left behind

bower.json, demo/px-data-grid-column-demo.html, px-data-grid-date-renderer.html, px-data-grid-number-renderer.html, px-data-grid-renderer-mixin.html, px-data-grid-string-renderer.html, px-data-grid.html
=> Datetime picker and dom-ifs

px-data-grid-theme.html, px-data-grid.html
Fixed #257 and missing columnTree error
=> Fixed disappearing border and missing columnTree error

px-data-grid-theme.html
I missed two variable defaults, adding those now. No need to make new release because of these.
=> Adding two color variables that did not have defauts

px-data-grid-cell-content-wrapper.html
=> fix(px-data-grid-cell-content-wrapper): prevent undefined values

px-auto-filter-field.html, px-data-grid-navigation.html, px-data-grid-selection-column.html, px-data-grid-toggle-details-column.html
=> Selection column: wrap _pxDataGrid usage into afterNextRender

px-data-grid.html, test/.eslintrc.json, test/helpers.html, test/px-data-grid-fixture.html, test/sorting.js
=> Local data failed to return original state after sorting

css/px-data-grid-header-cell-styles.html, sass/px-data-grid-header-cell.scss
=> Make column dropdown options capitalized correctly

px-data-grid.html
=> Do not give undefined value to column frozen

px-data-grid-edit-buttons.html
=> Reorder apply and cancel buttons in edit mode

px-data-grid.html, test/columns-api.js, test/generated-columns.js
=> Added id to columns

sass/px-data-grid-selection-column.scss
=> Add spacing before label in select column

demo/px-data-grid-remote-data-provider-demo.html, px-data-grid.html, test/remote-data-provider.js
=> Give page size to vaadin-grid

px-data-grid-cell-content-wrapper.html, px-data-grid.html
Fixes #320 #322 #318
removeProperty does not work at least with Chrome, setting to null does.
=> Fix bundle of highlighting issues

px-data-grid-filter-entity.html, px-data-grid-filter-section.html, px-data-grid-filter.html, px-data-grid-filters-modal.html, px-data-grid-filters-preview-tooltip.html, px-data-grid-filters-preview.html, px-data-grid.html
=> Added localization for non-localized strings

px-data-grid-filters-modal.html, px-data-grid-filters-preview.html, px-data-grid.html
=> Fixed broken "See all" link

px-data-grid-filters-modal.html
=> Renamed Apply and Reject buttons

px-data-grid.html, test/helpers.html
=> Added default renderer for generated columns

px-data-grid-paginated.html
=> Fixing type in pagination for #360

demo/px-data-grid-demo.html, px-data-grid.html
Wrong size value given to callback, fixed now. Ready for review.
Fixes #388
=> Add generated columns to demo to see the issue

px-data-grid-paginated.html
Fixes #328
When changing page size the page number is validated and reset to 1 if invalid.
=> Fixes #328: Adding page number validity check

px-data-grid-paginated.html
Fix issue where unsorting doesn't update order back to original
=> Copy old fix from px-data-grid to px-data-grid-paginated

px-data-grid-edit-buttons.html, px-data-grid.html
=> Stop propagation of edit button clicks to prevent selection

px-data-grid-paginated.html
=> Ready might be called after _wrapDataProvider

demo/px-data-grid-paginated-demo.html, px-data-grid-paginated.html
=> Pass columns from paginated to grid

demo/px-data-grid-column-demo.html, px-data-grid.html
Fixed #355
Also add initial support for column property resizable
=> Fix resizable prop pairing in column demo

demo/px-data-grid-column-demo.html, px-data-grid-cell-content-wrapper.html
=> Fix cell hover event with defined columns

px-data-grid-filter-entity.html
=> Added default values to filter entity

px-data-grid-cell-content-wrapper.html
=> Fixes bug with '0' value

css/px-data-grid-edit-buttons-styles.html, sass/px-data-grid-edit-buttons.scss
* Use pointer cursor for edit buttons
* Fix var() syntax bug so borders have a default color when CSS variable is not defined
Fixes #395.
=> Fix visual bugs with unthemed edit buttons

demo/px-data-grid-column-demo.html, demo/px-data-grid-demo.html, demo/px-data-grid-paginated-demo.html, demo/px-data-grid-remote-data-provider-demo.html, demo/px-data-grid-row-details-demo.html, px-data-grid-paginated.html, px-data-grid.html
Fixes #400
Now action is shown by default
=> API change replace actionMenu property with hideActionMenu

px-data-grid-paginated.html, px-data-grid.html
=> Fix auto filtering in pagination

sass/px-data-grid-filter-entity.scss, sass/px-data-grid-filter-section.scss, sass/px-data-grid-filter.scss
=> Do not use flex layout where not needed

px-data-grid-filter-entity.html, px-data-grid-filters-preview-tooltip.html, px-data-grid-filters-preview.html, px-data-grid.html
Added ability to select 'greater than' and 'less than' separately.
Fixes #404
=> Added min and max properties for column

px-data-grid-filter-entity.html, px-data-grid-filterable-mixin.html, px-data-grid-filters-modal.html, px-data-grid-filters-preview-tooltip.html, px-data-grid-filters-preview.html, px-data-grid.html
Simplified some logic as well.
Made mixin with advanced filter's logic in order to decrease the amount of code in px-data-grid and improve readability.
Also fixed #358
=> Added any column feature

px-data-grid-filterable-mixin.html
=> Fix wrong property name in event listener

px-data-grid.html
=> Disable striping when grouped by value

px-data-grid.html, sass/px-data-grid-header-cell.scss
=> Do not try to capitalize header dropdown options

px-data-grid-paginated.html
I probably have to approve this by myself
=> Just fast workaround for undefined _pxDataGrid

px-data-grid-navigation.html, sass/px-data-grid-navigation.scss
Related to issue #336 - Doesn't fix it, but change itself is still valid. So can be merged.
=> Disable clear from pagesize dropdown

px-data-grid-filter-entity.html
Simple change, fix number filtering
=> Remove extends that should not be there

px-data-grid-date-renderer.html, px-data-grid-number-renderer.html
=> Do not convert empty string to date or number

px-data-grid-filter-entity.html, px-data-grid-filterable-mixin.html, px-data-grid.html, test/filterable.js, test/px-data-grid-fixture.html
Also fixed some logic mistakes, that were found during tests writing.
=> Added tests for advanced filtering

px-data-grid-number-renderer.html
Fixes #463 
To test this, you need to remove type="number" or use browser that allows to write letters to field.
@Toshegg - feel free to improve this, this was my fast and ugly try to fix the issue.
=> Trying to prevent NaN values with some browsers

px-data-grid-paginated.html, px-data-grid.html
Fixes #443 
I used toUpperCase as toLowerCase has more different outcomes with different locales.
=> Do string compares incasesensitive way

px-data-grid-filter-entity.html, px-data-grid-filters-preview-tooltip.html, px-data-grid-filters-preview.html
Fixes #453
Also localized the Any correctly in chip.
=> Use proper names of columns in dropdown and chips

px-data-grid-header-cell.html, px-data-grid-sorter.html
=> fix(a11y): fix sorting with keyboard

px-data-grid-filter-entity.html, px-data-grid-filterable-mixin.html, px-data-grid-filters-preview-tooltip.html, px-data-grid-filters-preview.html, test/filterable.js
Fixes #451 
Fixes #452 
Fixes #457
=> Added missing conditions for numbers

bower.json, px-data-grid-filter-entity.html
=> Use new mode of px-rangepicker

sass/px-data-grid-header-cell.scss
=> Adjusting font-size of header dropdown

demo/px-data-grid-remote-data-provider-demo.html, px-data-grid-filterable-mixin.html, px-data-grid.html
Fix #458 
@alump, please, **double check** that it acts like you expected.
=> Add advanced filter's rules to params

px-data-grid-api.json, px-data-grid-paginated-api.json, px-data-grid.html
=> Improve the columns documentation

px-data-grid-filter-section.html, px-data-grid-filters-modal.html, sass/px-data-grid-filter-section.scss, sass/px-data-grid-shared.scss
Fixes #524 
Fixes #529 
Fixes #522
=> Minor layout and stylename fixes to advanced filtering

demo/px-data-grid-paginated-demo.html, px-data-grid-paginated.html
=> Add editable property to px-data-grid-paginated

demo/px-data-grid-column-demo.html, demo/px-data-grid-demo.html, px-data-grid-filter-entity.html, px-data-grid-filter-section.html, px-data-grid-filter.html, px-data-grid-filters-modal.html, px-data-grid.html, sass/px-data-grid-filter-entity.scss
=> Adding compact advanced filter dialog option

px-data-grid-theme.html, sass/px-data-grid-dark-theme.scss, sass/px-data-grid-light-theme.scss
Fixed group-by to have a different color (gray4/gray14) than selected (gray5/gray13).\
Fixes #439
=> Group by was using the same color as selected, added new variable

px-data-grid-api.json, px-data-grid-column.html, px-data-grid-header-cell.html, px-data-grid-paginated-api.json, px-data-grid.html
=> Make "Group by Column" and "Expandable Rows" exclusive

px-data-grid-paginated.html, px-data-grid.html
=> Fix observing changes in local data provider

px-data-grid-paginated.html
Fixes #567
My bad :man_facepalming: with this issue.
=> Make sure _pxDataGrid is defined before using it

px-data-grid.html, test/column-dropdown-menu.js
=> Put frozen columns in place of the first data column

demo/px-data-grid-column-demo.html, demo/px-data-grid-custom-renderer-demo.html, demo/px-data-grid-demo.html, demo/px-data-grid-highlight-demo.html, demo/px-data-grid-paginated-demo.html, demo/px-data-grid-row-details-demo.html, px-data-grid-paginated.html, px-data-grid.html
=> Fix selection by partially reverting PR #563

px-data-grid-paginated.html, px-data-grid.html
Connected to https://github.com/vaadin/px-data-grid/pull/551 and fix forgotten in https://github.com/vaadin/px-data-grid/pull/563 2 lines
=> Fix _tableDataChanged observer params

test/px-data-grid-navigation-test.js, test/px-data-grid-paginated-test.js
=> Fix running pagination and navigation tests

px-data-grid-filters-modal.html, px-data-grid.html
=> Do not listen advanced filter open request via document

demo/px-data-grid-remote-data-provider-demo.html
Fixes https://github.com/vaadin/px-data-grid/issues/112
=> Handle network issues in the remote-data-provided example

demo/px-data-grid-column-demo.html, px-data-grid-filter-entity.html, px-data-grid-filter-section.html, px-data-grid-filter.html, px-data-grid-filters-modal.html, px-data-grid-paginated.html, px-data-grid.html
Default is show all (happens if values are undefined or empty
arrays)
=> Add API to define what comparators are offered

px-data-grid.html
=> Fix grouping by column after advanced filtering

sass/px-data-grid.scss
=> Fix action icons for IE11

px-data-grid-filters-preview.html
=> Use rendererConfig.displayFormat for date chips if provided, otherwise ISO format

px-data-grid-filterable-mixin.html, px-data-grid-number-renderer.html
=> Allow decimals, add numbers formatting

demo/px-data-grid-column-demo.html, px-data-grid-filters-preview.html, sass/px-data-grid-filters-preview.scss
Related to #653 
Updating default chip date format and chip tooltip format for filter chips.
=> Updating filter chip and tooltip for date filters

examples/custom-renderer.html, px-data-grid-column.html, px-data-grid-header-cell.html, test/column-dropdown-menu.js
=> Ensure groupByColumnAllowed is passed down whenever it changes

px-data-grid-column.html
=> Make _element configurable (overridable)

px-data-grid-navigation.html
=> Add disable-truncate for page-size-select px-dropdown

px-data-grid.html
=> Action menu: set selected items after setting its content

px-data-grid-filter-section.html, px-data-grid-filters-modal.html
Depends on https://github.com/predixdesignsystem/px-modal/pull/38
Resolves #475
=> Implement keyboard accessibility for advanced filtering modal

px-data-grid.html
Fix for #769 
Using momentJS to handle sorting of all dates/timestamps regardless of format or timezone.
=> Adding proper sorting for timestamps

px-data-grid-navigation.html, px-data-grid-paginated-api.json, px-data-grid-paginated.html, test/px-data-grid-navigation-test.js, test/px-data-grid-paginated-test.js
Set to automatically hide the page size select (dropdown) when there is only 1 page available and it's smaller or equal to the smallest of the selectable page sizes.
=> Add new property 'autoHidePageSizeSelect'
